#!/bin/bash

openBS() {
    mkdir ~/bomb-shelter
    s3fs -o allow_other,uid=$UID,umask=22 bomb-shelter $HOME/bomb-shelter && echo "bomb-shelter at ~/bombshelter"
}

closeBS() {
    HOSTNAME=hostname
    sudo umount $HOME/bomb-shelter && echo "disconnected bomb-shelter from $HOSTNAME"
    rm -r $HOME/bomb-shelter
}
