#!/bin/bash

# Comp class directory
# Usage: cs CLASS_CODE [WEEK]
cs() {

    SEM="18s1"
    # Just goes to root of gits
    if [ "$#" -eq "0" ]; then
        cd ~/git/
        ls
    elif [ -d ~/git/comp"$1_${SEM}" ]; then
        cd ~/git/comp"$1_${SEM}"/
            
        # If week/ass given
        if [ "$#" -eq "2" ]; then

            # If week given 
            if [ -d week"$2"/lab ]; then    # CDs INTO WEEK
                cd week"$2"/lab/
                ls
            # If ass give
            elif [ "$2" = "ass" ]; then    # CDs INTO ASSIGNMENT
                case "$1" in
                    #CLASS_CODE)
                    #   cd ASSIGNMENT_FOLDER
                    #   ls;;
                    3231) 
                        cd Synchronisation-3231-18s1
                        ls;;
                    2511)
                        cd Cinema_Booking_System-3231-18s1
                        ls;;
                    *) echo "Assignment NOT specified for class COMP$1";;
                esac

            else                            # Week not found
                printf "Week \"$2\" doesn't exist.\n"
                printf "Create 'week$2' folder? [y/N] " && read answer
                if [[ $answer == y* ]] || [[ $answer == Y* ]] ; then
                    mkcd "week$2/lab"
                fi
            fi

        # No week/ass given
        else
            ls
        fi
    else # Doesn't exist
        printf "Class \"$1\" doesn't exist.\n"
    fi
}

classes() {
    cd ~/git && cat classes
}
