#!/bin/bash

inOS() {
    in=$(echo $PATH | grep "3231" | wc -l)
    if [[ "$in" == "1" ]]; then
        echo "You're in a 3231 subshell"
    else
        echo "You're NOT in a 3231 subshell"
    fi
}
