#!/bin/bash

newJava() {

    if [[ $# -eq 1 ]]; then
        touch $1.java
        echo -e "\npublic class $1 {" >> $1.java
        echo -e "\n\tpublic $1() {" >> $1.java
        echo -e "\n\t}" >> $1.java
        echo -e "\n}" >> $1.java
    else
        echo "USAGE: newJava CLASS_NAME"
    fi
}
