#!/bin/bash

print256() {
    for i in {0..255}; do

        # Alignment
        if (( $i <= 9 )); then
            printf "  "
        elif (( $i >= 10 && $i <= 99 )); then
            printf " "
        fi

        # Colour
        printf "\x1b[38;5;${i}mcolour${i}\x1b[0m "
        
        # Every 8, newline
        if ! (( ($i+1) % 8 || $i == 0)); then
            printf "\n"
        fi
    done
}
