#! /bin/bash

alias destroy='/bin/rm'

rm() {
    mkdir -p ~/.trash/
    mv "$1" ~/.trash/
}

emptytrash() {
    echo -n "Really empty Trash? DESTRUCTIVE [y/N] " && read answer
    if [[ $answer == y* ]] || [[ $answer == Y* ]] ; then
        destroy -rf ~/.trash/* && echo "Emptied Trash!"
    else 
        echo "Not emptying trash"
    fi
}


