#!/bin/bash

tm() {

    host=$(hostname | cut -d . -f 1 | tr '[:lower:]' '[:upper:]')

    if [[ $# -eq 0 ]]; then
        if [[ $(tmux ls 2> /dev/null | grep "$host" | wc -l) -ge 1 ]]; then
            tmux attach -t $host
        else
            tmux new-session -s $host
        fi
    elif [[ $# -eq 1 ]]; then
        alreadySession=$(tmux ls 2> /dev/null | grep "$1" | wc -l)
        if [[ $1 == "ls" ]]; then
            tmux ls
        elif [[ $alreadySession -eq 1 ]]; then
            tmux attach -t $1
        else
            if [[ $(cs 2> /dev/null | grep "$1" | wc -l) -ge 1 ]]; then
                cs $1 1> /dev/null && tmux new-session -s $1_$host
            else
                tmux new-session -s $1_$host
            fi
        fi
    else
        echo "USAGE: tmux [NAME/CLASS_CODE]"
    fi
}
