#!/bin/bash

tm() {

    host=$(hostname | cut -d . -f 1 | tr '[:lower:]' '[:upper:]')

    if [[ $# -eq 0 ]]; then
        tmux new-session -s $host
    elif [[ $# -eq 1 ]]; then
        if [[ $(tmux ls 2> /dev/null | grep "$1_$host" | wc -l) -eq 0 ]]; then
            cs $1 1> /dev/null && tmux new-session -s $1_$host
        else
            tmux attach -t $1_$host
        fi
    else
        echo "USAGE: tmux [CLASS_CODE]"
    fi
}
